// Hero frame sequence — optimized WebP generated by scripts/build-frames.mjs.
export const FRAME_COUNT = 300;

export const framePath = (i: number) =>
  `/frames/frame_${String(i).padStart(3, "0")}.webp`;

// How many frames to have decoded before the hero is considered "ready".
export const WARM_FRAMES = 24;

export const POSTER_START = "/poster-start.webp";
export const POSTER_END = "/poster-end.webp";
